force-app/main/default/objects/Rest_Service_Config__mdt/Rest_Service_Config__mdt.object-meta.xml
<CustomObject>
    <label>Rest Service Configuration</label>
    <pluralLabel>Rest Service Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Rest_Service_Config__mdt/fields/Api_Key__c.field-meta.xml
<CustomField>
    <fullName>Api_Key__c</fullName>
    <description>The api key required to authenticate into the rest service.</description>
    <label>Api Key</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rest_Service_Config__mdt/fields/Batch_size__c.field-meta.xml
<CustomField>
    <fullName>Batch_size__c</fullName>
    <description>The number of records that will be processed in a single execution.</description>
    <label>Batch size</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rest_Service_Config__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint to use in callouts</description>
    <label>Endpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Rest_Service_Config__mdt/fields/Page_Limit__c.field-meta.xml
<CustomField>
    <fullName>Page_Limit__c</fullName>
    <description>Limit on the amount of pages the rest service has, in the case it uses a paginator</description>
    <label>Page Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rest_Service_Config__mdt/fields/Result_Number__c.field-meta.xml
<CustomField>
    <fullName>Result_Number__c</fullName>
    <description>The minimum amount of results to retreive from the rest service</description>
    <label>Result Number</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RestServiceConfigsSelector.cls
public with sharing class RestServiceConfigsSelector extends fflib_SObjectSelector{
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            Rest_Service_Config__mdt.Api_Key__c,
            Rest_Service_Config__mdt.Batch_size__c,
            Rest_Service_Config__mdt.Endpoint__c,
            Rest_Service_Config__mdt.Page_Limit__c,
            Rest_Service_Config__mdt.Result_Number__c
        };
    }

    public Schema.SObjectType getSObjectType()
    {
        return Rest_Service_Config__mdt.SObjectType;
    }

    public Rest_Service_Config__mdt[] selectByDeveloperName(Set<String> restServicesNames){
        fflib_QueryFactory queryFactory = newQueryFactory();
        return (Rest_Service_Config__mdt[]) Database.query(queryFactory.setCondition('DeveloperName IN :restServicesNames').toSoql());
    }
}